name: CI

on:
  push:
    branches:
    - devel
    - master
    - "release-*"
  pull_request:
    branches:
    - devel
    - master
    - "release-*"
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest

    name: 'typecheck: mypy'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install
        run: |
          set -euo pipefail
          pip install mypy
          pip install .
      - name: Typecheck
        run: |
          python -m mypy --config mypy.ini -p aioopenssl

  linting:
    runs-on: ubuntu-latest

    name: 'lint: flake8'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install
        run: |
          set -euo pipefail
          pip install flake8
      - name: Linting
        run: |
          python -m flake8 aioopenssl tests

  test:
    needs:
    - mypy
    - linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
        - '3.5'
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'

    name: 'unit: py${{ matrix.python-version }}'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install
        run: |
          set -euo pipefail
          pip install nose coveralls pyOpenSSL
          pip install .
      - name: Run tests
        run: |
          set -euo pipefail
          python -m nose --with-cover --cover-package aioopenssl tests
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    name: Finalize
    steps:
    - name: Finalize Coveralls interaction
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
